title: Bennington Area Makers
description: Community making in Bennington, Vermont. Home of Bennington Area Robotics.
url: https://www.bamvt.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - resources

collections:
  events:
    output: true
